export default {
	// base
	base_index: '/pages/base/index',
	base_button: '/pages/base/button',
	base_icon: '/pages/base/icon',
	base_cell: '/pages/base/cell',
	base_input: '/pages/base/input',
	base_tag: '/pages/base/tag',
	base_radio: '/pages/base/radio',
	base_search: '/pages/base/search',
	base_segment: '/pages/base/segment',
	base_stepper: '/pages/base/stepper',
	base_switch: '/pages/base/switch',
	base_title: '/pages/base/title',
	base_progress: '/pages/base/progress',
	base_tabs: '/pages/base/tabs',
	base_grid: '/pages/base/grid',
	base_countdown: '/pages/base/countdown',
	// pop
	pop_index: '/pages/pop/index',
	// navbar
	navbar_index: '/pages/navbar/index',
	// tabbar
	tabbar_index: '/pages/tabbar/index',
	tabbar_hump: '/pages/tabbar/hump',
	tabbar_hump_text: '/pages/tabbar/hump_text',
	tabbar_hump_border: '/pages/tabbar/hump_border',
	tabbar_normal: '/pages/tabbar/normal',
	tabbar_no_text: '/pages/tabbar/no_text',
	// picker
	picker_index: '/pages/picker/index',
	// filter
	filter_index: '/pages/filter/index',
	filter_nav_down: '/pages/filter/nav_down',
	filter_down: '/pages/filter/down',
	filter_more_down: '/pages/filter/more_down',
	filter_up: '/pages/filter/up',
	filter_more_up: '/pages/filter/more_up',
	// swiper
	swiper_index: '/pages/swiper/index',
	// scroll
	scroll_test: '/pages/scroll/test/test',
	scroll_raw: '/pages/scroll/test/raw',
	scroll_raw_one: '/pages/scroll/test/raw_one',
	scroll_raw_wrap: '/pages/scroll/test/raw_wrap',
	scroll_raw_one_wrap: '/pages/scroll/test/raw_one_wrap',
	scroll_custom: '/pages/scroll/test/custom',
	scroll_custom_one: '/pages/scroll/test/custom_one',
	scroll_custom_wrap: '/pages/scroll/test/custom_wrap',
	scroll_custom_one_wrap: '/pages/scroll/test/custom_one_wrap',
	scroll_load_more: '/pages/scroll/test/load_more',
	scroll_load_more_one: '/pages/scroll/test/load_more_one',
	scroll_load_more_wrap: '/pages/scroll/test/load_more_wrap',
	scroll_load_more_one_wrap: '/pages/scroll/test/load_more_one_wrap',
	scroll_test_header: '/pages/scroll/test/header',
	scroll_index: '/pages/scroll/index',
	scroll_h: '/pages/scroll/h',
	scroll_header: '/pages/scroll/header',
	scroll_header_refresh: '/pages/scroll/header_refresh',
	scroll_list_simple: '/pages/scroll/list_simple',
	scroll_list_loading: '/pages/scroll/list_loading',
	scroll_list_more: "/pages/scroll/list_more",
	scroll_waterfall: '/pages/scroll/waterfall',
	scroll_x_support: '/pages/scroll/x_support',
	// others
	others_index: '/pages/others/index',
	// helper
	about: '/pages/helper/about'
}
