// recommend
export const recommends = [{
	icon: 'solid-camera',
	name: '基础',
	page: 'base_index'
}, {
	icon: 'solid-location',
	name: '列表',
	page: 'scroll_index'
}, {
	icon: 'solid-fire',
	name: 'swiper',
	page: 'swiper_index'
}, {
	icon: 'solid-calendar',
	name: '筛选',
	page: 'filter_index'
}, {
	icon: 'radio-button',
	name: '弹层',
	page: 'pop_index'
}]

export const bigCats = [{
	icon: 'radio-button',
	name: '基础组件',
	type: 'base_index',
	title: '主题配置，细节到位',
	intro: '图标 按钮 输入框 单元格 格子 标签 ...',
	hint: '查看具体'
}, {
	icon: 'bold-refresh',
	name: '下拉上提',
	type: 'scroll_index',
	title: 'scroll和list',
	intro: '分别对mp/h5/app端做了下拉与上提',
	hint: '试试感觉'
}, {
	icon: 'warning',
	name: '弹层互动',
	type: 'pop_index',
	title: '性能好，动画支持',
	intro: '弹窗 Modal 遮罩 Loading Toast ActionSheet...',
	hint: '前往体验'
}, {
	icon: 'solid-circle-right',
	name: '导航栏',
	type: 'nav_navbar',
	title: '完全自定义',
	intro: '默认与随心所欲之间，没有限制',
	hint: '查看样板'
}, {
	icon: 'album',
	name: '弹层选择',
	type: 'filter_index',
	title: 'filter/down-up',
	intro: '选择filter/dropdown，等',
	hint: '马上感受'
}, {
	icon: 'task',
	name: '抽屉/拖动',
	type: 'drawer_index',
	title: '抽屉/拖动',
	intro: '抽屉，拉出，拖动，回收，等',
	hint: '现在就看'
}, {
	icon: 'topic',
	name: 'Picker',
	type: 'picker_index',
	title: '各种picker',
	intro: 'myp-popup封装的picker示范',
	hint: '体验一下'
}, {
	icon: 'solid-plus',
	name: 'Tabbar',
	type: 'tabbar_index',
	title: '非swiper实现',
	intro: '支持各种细节微调，图片/icon/text/badge/dot',
	hint: '马上体验'
}, {
	icon: 'rows',
	name: 'Swiper',
	type: 'swiper_index',
	title: 'Swiper示范',
	intro: 'swiper列表，带头部的swiper列表',
	hint: '试下手感'
}, {
	icon: 'headphone',
	name: 'ScrollScale',
	type: 'scroll_h_index',
	title: '滚动缩放，余弦放大，自动居中',
	intro: '横向滚动，滚动缩放，余弦放大，自动居中',
	hint: '现在就看'
}, {
	icon: 'radio',
	name: '其它',
	type: 'others_index',
	title: '组件或页面',
	intro: '常用的一些UI设计，以及页面',
	hint: '去瞄一下'
}]

// 布局
export const flexs = [{
	cover: 'https://mypui.asnowsoft.cn/imgs/c1.jpg',
	title: '布局：myp-flex',
	desc: '横向/竖向快速布局的组件化，提供组件化布局能力',
	page: 'flex_flex'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c3.jpg',
	title: '测距：myp-wing',
	desc: '左右横向距离配置，组件化测距',
	page: 'flex_wing'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c7.jpg',
	title: '间距：myp-space',
	desc: '上下距离配置，组件化间距设置',
	page: 'flex_space'
}]
// 列表与盒子
export const boxes = [{
	cover: 'https://mypui.asnowsoft.cn/imgs/c10.jpg',
	title: '[myp-list]刷新加载列表',
	label: '列表',
	page: 'scroll_list_more'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c7.jpg',
	title: '[myp-list-simple]纯列表',
	label: '列表',
	page: 'scroll_list_simple'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c4.jpg',
	title: '[myp-waterfall]瀑布流',
	label: '瀑布',
	page: 'scroll_waterfall'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c12.jpg',
	title: '[myp-scroll-h]横向列表',
	label: '列表',
	page: 'scroll_h'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c4.jpg',
	title: '[myp-list-index]索引列表',
	label: '索引',
	page: 'base_indexlist'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c7.jpg',
	title: '[myp-content-box]高度盒子',
	label: '盒子',
	page: 'base_content_box'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c1.jpg',
	title: '[myp-height]高度盒子',
	label: '盒子',
	page: 'base_height'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c10.jpg',
	title: '[myp-status]状态栏',
	label: '盒子',
	page: 'base_height'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c3.jpg',
	title: '[myp-xbar]底部安全区',
	label: '盒子',
	page: 'base_height'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c7.jpg',
	title: '[myp-position]定位盒子',
	label: '定位',
	page: 'base_position'
}]
// 导航
export const navs = [{
	avatar: 'https://mypui.asnowsoft.cn/imgs/bear.jpg',
	name: '导航栏',
	cares: 'myp-navbar',
	intro: '支持定位与占位',
	page: 'nav_navbar'
}, {
	avatar: 'https://mypui.asnowsoft.cn/imgs/cat.jpg',
	name: 'tabbar',
	cares: 'myp-tabbar',
	intro: '凹凸都可以',
	page: 'tabbar_index'
}, {
	avatar: 'https://mypui.asnowsoft.cn/imgs/pig.jpg',
	name: '横向tabs',
	cares: 'myp-tabs-h',
	intro: '可与进度联动',
	page: 'base_tabs'
}, {
	avatar: 'https://mypui.asnowsoft.cn/imgs/girl.jpg',
	name: '竖向tabs',
	cares: 'myp-tabs-v',
	intro: '竖向切换tabs',
	page: 'base_tabs'
}, {
	avatar: 'https://mypui.asnowsoft.cn/imgs/hen.jpg',
	name: '抽屉',
	cares: 'myp-drawer',
	intro: '可拖动抽屉/菜单',
	page: 'drawer_index'
}, {
	avatar: 'https://mypui.asnowsoft.cn/imgs/cat.jpg',
	name: '气泡',
	cares: 'myp-popover',
	intro: '气泡弹层/引导',
	page: 'nav_popover'
}]
// 数据输入
export const inputs = [{
	cover: 'https://mypui.asnowsoft.cn/imgs/c3.jpg',
	title: 'myp-button',
	label: '按钮',
	page: 'base_button'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c12.jpg',
	title: 'myp-input',
	label: '输入框',
	page: 'base_input'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c11.jpg',
	title: 'myp-input-one',
	label: '4-6验证码',
	page: 'base_input'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c10.jpg',
	title: 'myp-switch',
	label: '开关',
	page: 'base_switch'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c4.jpg',
	title: 'myp-search',
	label: '搜索框',
	page: 'base_search'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c7.jpg',
	title: 'myp-check',
	label: '单多选',
	page: 'base_check'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c1.jpg',
	title: 'myp-select',
	label: '选择',
	page: 'base_select'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c3.jpg',
	title: 'myp-stepper',
	label: '步进器',
	page: 'base_stepper'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c5.jpg',
	title: 'myp-slider',
	label: '区间',
	page: 'base_slider'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c6.jpg',
	title: 'myp-picker',
	label: '选择器',
	page: 'picker_index'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c7.jpg',
	title: 'myp-picker-time',
	label: '时间选择器',
	page: 'picker_index'
}]
// 数据展示
export const displays = [{
	cover: 'https://mypui.asnowsoft.cn/imgs/c10.jpg',
	title: 'myp-grid',
	desc: '宫格：支持badge',
	label: '宫格',
	page: 'base_grid'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c1.jpg',
	title: 'myp-cell',
	desc: '单元：icon-label-value-indicator四段式',
	label: '单元',
	page: 'base_cell'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c2.jpg',
	title: 'myp-icon',
	desc: '图标：字体图标，支持图片',
	label: '图标',
	page: 'base_icon'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c7.jpg',
	title: 'myp-item',
	desc: 'item：上下item',
	label: 'item',
	page: 'base_item'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c3.jpg',
	title: 'myp-title',
	desc: '标题：左中右三段式自定义标题',
	label: '标题',
	page: 'base_title'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c4.jpg',
	title: 'myp-tag',
	desc: '标签：支持badge',
	label: '标签',
	page: 'base_tag'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c5.jpg',
	title: 'myp-tag-group',
	desc: '标签群：支持单多选',
	label: '标签',
	page: 'base_tag'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c6.jpg',
	title: 'myp-badge',
	desc: '角标：支持原点/文字',
	label: '角标',
	page: 'base_badge'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c7.jpg',
	title: 'myp-countdown',
	desc: '倒计时：自定义格式的倒计时',
	label: '倒计时',
	page: 'base_countdown'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c8.jpg',
	title: 'myp-divider',
	desc: '分割线：无情无聊的分割线',
	label: '分割线',
	page: 'base_divider'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c9.jpg',
	title: 'myp-progress',
	desc: '进度条：开放自由，随心所欲',
	label: '进度条',
	page: 'base_progress'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c10.jpg',
	title: 'myp-progress-circle',
	desc: '进度条：环状。纯css实现',
	label: '进度条',
	page: 'base_progress_circle'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c3.jpg',
	title: 'myp-timeline-item',
	desc: '时间轴：百变自由',
	label: '时间轴',
	page: 'base_timeline'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c11.jpg',
	title: 'myp-result',
	desc: '结果：结果展示页面，成功/失败...',
	label: '结果',
	page: 'base_result'
}]
// 反馈互动
export const interacts = [{
	cover: 'https://mypui.asnowsoft.cn/imgs/c12.jpg',
	title: 'myp-popup',
	label: '弹窗',
	page: 'pop_index'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c3.jpg',
	title: 'myp-popup-always',
	label: '弹窗',
	page: 'pop_index'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c4.jpg',
	title: 'myp-toast：提示',
	label: 'toast',
	page: 'pop_index'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c10.jpg',
	title: 'myp-loading：加载中，支持遮罩',
	label: 'loading',
	page: 'pop_index'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c7.jpg',
	title: 'myp-notice：提示',
	label: 'notice',
	page: 'pop_index'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c12.jpg',
	title: 'myp-notice-dynamic：动态提示',
	label: 'notice',
	page: 'pop_index'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c3.jpg',
	title: 'myp-overlay',
	label: '遮罩',
	page: 'pop_index'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c4.jpg',
	title: 'myp-fold',
	label: '收展',
	page: 'base_fold'
}, {
	cover: 'https://mypui.asnowsoft.cn/imgs/c6.jpg',
	title: 'myp-loading-indicator',
	label: '指示器',
	page: 'base_loading_indicator'
}]
// 手势
export const gestures = [{
		img: 'https://mypui.asnowsoft.cn/imgs/c3.jpg',
		maskType: 'mask',
		title: '刷新',
		icon: 'solid-calendar',
		tag: '',
		desc: 'myp-refresher',
		descIcon: '',
		bgType: '',
		titleType: 'inverse',
		descType: 'inverse',
		iconType: 'inverse',
		iconStyle: 'font-size:54rpx;',
		page: 'scroll_list_more'
	},
	{
		img: 'https://mypui.asnowsoft.cn/imgs/c7.jpg',
		maskType: 'mask',
		title: '刷新',
		icon: 'solid-plus',
		tag: '',
		desc: 'myp-refresher-n',
		descIcon: '',
		bgType: '',
		titleType: 'inverse',
		descType: 'inverse',
		iconType: 'inverse',
		iconStyle: 'font-size:54rpx;',
		page: 'scroll_list_more'
	},
	{
		img: '',
		maskType: 'none',
		title: '加载',
		icon: 'solid-camera',
		tag: '推荐',
		desc: 'myp-loader',
		descIcon: '',
		bgType: 'dark',
		titleType: 'text',
		descType: 'third',
		iconType: 'text',
		iconStyle: 'font-size:54rpx;',
		page: 'scroll_list_more'
	},
	{
		img: '',
		maskType: 'none',
		title: '加载',
		icon: 'solid-play',
		tag: '推荐',
		desc: 'myp-loader-n',
		descIcon: '',
		bgType: 'dark',
		titleType: 'text',
		descType: 'third',
		iconType: 'text',
		iconStyle: 'font-size:54rpx;',
		page: 'scroll_list_loading'
	}
]
